services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - notebook_shared:/notebook_output
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - NOTEBOOK_URL=http://notebook:7000
      - ALLOWED_ORIGINS=http://frontend:3000,http://localhost:3000
    depends_on:
      - notebook
    networks:
      - app-network
    
  notebook:
    build: ./notebook
    ports:
      - "7000:7000"
    volumes:
      - ./notebook:/backend
      - notebook_shared:/notebook_output
    environment:
      - ALLOWED_ORIGINS=http://backend:5000,http://localhost:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  notebook_shared:

